name: Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Setup Release Credentials
        env:
          RUBYGEMS_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 600 $HOME/.gem/credentials
          echo "---" >$HOME/.gem/credentials
          echo -e ":rubygems_api_key: ${RUBYGEMS_API_KEY}" > $HOME/.gem/credentials

      - name: Publish Gem to RubyGems
        run: |
          gem build
          gem push *.gem
